language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-26.0.2
  - android-26
script:
  - "./gradlew build"
deploy:
  - provider: releases
    skip_cleanup: true
    file: "app/build/outputs/apk/debug/app-debug.apk"
    on:
      tags: true
    api_key:
      secure: VEFF5IWyypoYuu2s4fYDG8HujOFdD8mTKBa8FmJJOyOQxZXorhcrRRyoJUNno/cpVmJWmevS0AXcBLAlolh5R51YVnAIeb0AVcKNW3C4CCiy1F6J744PNAe59AivSTwY9ZwBDMKhm/u4gmVEmXPkomHT87mBuvFwrVxLDo6nmKb6hEX9zCx9ju/Qa+mhO7PyuYOhcAO1hA1I1kAdZALvzlCvl3rHsF6a5hrKuUfPlyeFy53B3GcW6Zv7UAmS0ZWaA91WgINofQblk06UatTNz911ih6cPdTnbbNePNHzOOWaXC9bAQ7Cs6IQVoNc/1CYK72mO/zD2w+uge5W7VzLX1yuSyOIKKDKz2sulH6oQP6q1QeVPqqBa2qhEfS82V7LXhJOIMSzKFd597S94bOO/Y+YFoqS1A8DAFXwNAJv9go39/k7IXu+gmGFTic8E9Gfc/z7t1VHJjNRuyS1uZRcj9hfd7kGJz/oz4Ps8UuePX6CRwxxwRrZeLU200mCZ0KmSqM1bBzPiWANT+d/zPhPfDjYBqNDIRvuNHFkRaR3Mw8HeF4b5R3FI1aInih7XkFc3t58AZYtuCsbSy3y8hG8aQiOYrHV3V3ixpV3kODocmChXzrHy7inHSr00rDPJWwssfop31T1dOTqlilg4ZpNFHzAN3jgZp+BeNZL7sKjHeI=
  - provider: bintray
    skip_cleanup: true
    file: "descriptor.json"
    on:
      tags: true
    user: leochuan
    key:
      secure: qHfqyFaQXqxA46ZaHtxzZ811tV+2sd+JWRZd2crzg43lLZH8NMBvBwiuSiP5a8/MYhnrviaw/LkZHso5+6SXyTbn3ET0N1Ksd2lI3FgZH4U35eLUwf6i/uNw9bqJ7TYBSO+o9sDaXciYjLkGdfVPQ7ihs/TTROr5Lag1tG1FccDXuVY6oGH2mfDCE8n38xyrjeL3oZKVk3PaUYeFlboergMrLwrVuk3vOy1o2i301uWq8YqcBynROxTObRPVd5hgF4cX5MOYhKUCqXrK6mwWTmRgCVVHe5+Dll6bnd5STCiR/0ymwbQXjPBdLXqqBrCxCWWkf/8aNIRaajDHaauDRMTQPW81NUeKNp76fvAqzq+CCzQDf4qa+jky1OsOntoah3yFvcAQlodCYWS+mAB4obilE3p8K2Z/joeCzb8uH+LlXOZ7asjK+FJ9jlCgiuXzienAbwQnU+Bm5fu4pxq+LgzvSovQVbC0e4oD+BL3eU5bGGc8QxkXFWvmIoQ5d2Uhw6epLleaxL2EEDPbPgakUzs3lp8b2qJ4afhDAiGs5W8knOFn7sxcRhpMzuOHxTJSVJBOj6Kkb7apHMzZa+ezQzdNwaw+Ad0YBkPRBQ2VCDzzv5wKtitTteRxWBJFsF63jLdsdkDOvt78+Svjtg5mNTGVft2YkGw70/gOE1ZXO0g=